name = "introduction-maker-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "introduction-maker-db"
database_id = "your-database-id-here" # wrangler d1 create で生成されるID

# R2 Storage
[[r2_buckets]]
binding = "R2"
bucket_name = "introduction-maker-images"

# Environment Variables
[vars]
ENVIRONMENT = "development"

# KV (必要に応じて)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"